### ISSUE TITLE
[Bug] Night Vision upgrades don't show up on terminal after upgrade cycle

### ISSUE THREAD

**Issue by ajsglist** [Malcolm-Q/LC-LateGameUpgrades#562]
Hey there,

After 1st quota I bought the first Night Vision upgrade + the first Quick Hands upgrade.  Then took off from the company, at which point the upgrades rotated in orbit.

I have the settings enabled to rotate on new quota, but to always show purchased upgrades.  I think Night Vision's upgrade may have some sort of override to ignore the "show purchased upgrades" option

![image](https://github.com/user-attachments/assets/e1892ef9-cae9-4bed-937d-842f1d9802af)
![image](https://github.com/user-attachments/assets/04e9aec4-3d4a-4784-8946-7aebf3cc7dcd)

Cheers

**Comment by ajsglist** [comment]
I also noticed that upon exiting a lobby and reloading, the upgrade pool was randomized in the middle of the quota.  Not a huge issue, but it would be nice if the behavior was consistent so that lobby reloads didn't trigger the shuffle if the "PerQuota" option was selected

**Comment by WhiteSpike** [comment]
Could be an issue of not saving the random seed. I will take a look

**Comment by WhiteSpike** [comment]
If you could check if 3.10.9 fixes this, that would be neat.

**Comment by ajsglist** [comment]
Upgraded to 3.10.9 and did the following: bought Protein Powder 1 + Quick Hands 1 --> played 1 day on experimentation --> went back to orbit --> saved/quit out of the lobby --> reloaded lobby

LGU upgrades have rerandomized, unfortunately.

![image](https://github.com/user-attachments/assets/8bcebd05-cb32-4a6c-a9bf-60692679f21e)

I just started testing v56 tonight, and haven't seen Night Vision upgrade but I will update you on that one when I see it

**Comment by ajsglist** [comment]
Also checked the night vision upgrade issue.  Bought NV 1 in orbit --> dropped on experimentation, grabbed some quick loot --> returned to orbit --> saved/quit --> reloaded lobby --> upgrades didn't reshuffle this time

So I guess it's not quite clear what is going on there or why it reshuffled the first time but not this time.

I then did 2 more quick days so I could trigger the next quota.  When the new quota shuffled upgrades, Night Vision was hidden again despite NV 1 being unlocked.

![image](https://github.com/user-attachments/assets/e3f07daf-48bc-4f65-876e-8f9b4d99e8cd)
![image](https://github.com/user-attachments/assets/c3b73df3-e005-4d01-b587-b87cb911b692)

I also noticed that Night Vision Goggles don't seem to have a scan node, for what it's worth

![image](https://github.com/user-attachments/assets/d09a7f2e-5911-4b05-ae97-999671e2bdf1)

**Comment by WhiteSpike** [comment]
There was another NV check I missed when hiding upgrades. That one at least should be solved by now.

I will try looking at the seed problem at better time. The scan node I'm not so sure what's going on, I haven't touched it in ages.

**Comment by ajsglist** [comment]
Appreciate the work.  The upgrade reshuffling isn't a gamebreaker or anything, so it's certainly not pressing.  I'll try to reproduce it when I have a bit of time and update.

I don't think the night vision scan node would be a recent thing.  I don't think it ever had a scan node.  Seemed to trivial to report on its own so I never made a ticket previously.

**Comment by WhiteSpike** [comment]
3.10.10 release should address the NV not showing a scan node. It was badly configured from the start (Switched min and max range values)

**Comment by ajsglist** [comment]
closing this out since NV scan and NV upgrade rotation were fixed

![image](https://github.com/user-attachments/assets/dd2efd7b-15a5-4a4c-a348-c3d7500a7dac)

**Comment by ajsglist** [comment]
I think I found the rerandomization error that was still present, that couldn't be reproduced reliably before.

Current steps:
1) load into new lobby/save file
2) in orbit, note current upgrade list
3) drop on a planet (I picked experimentation)
4) quit/save while on the planet, then reload into the lobby
5) pull up the LGU upgrade list to note it is now incorrect

in orbit:
![image](https://github.com/user-attachments/assets/abf1e916-e449-4057-a408-dba703b9b911)

after reloading file as described:
![image](https://github.com/user-attachments/assets/24ab6b8f-5f58-4a3c-8bea-84e1a6ddf59d)

I've used the steps above to reproduce the issue 3x times now

Cheers

**Comment by WhiteSpike** [comment]
It seems I am unable to replicate the issue you're describing, despite following the steps, from the test build.

Maybe I accidentaly fixed it while I was fixing the issue where the host's save would be overriden from the first joining client or some unknown interaction with some other mod is preventing the randomization from executing on that scenario. 

I just find it odd that it doesn't do it anymore if you refresh the game.

**Comment by WhiteSpike** [comment]
Closing due to inactivity and unable to consistenly reproduce this behaviour.
You can decide to open a new issue if this is still ongoing (as I have been away for a long time due to work and things could have changed meanwhile with other mods.)
